### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'getItem' of null

### ISSUE THREAD

**Issue by foliodev** [cotterapp/cotter-js#11]
Uncaught (in promise) TypeError: Cannot read property 'getItem' of null

 value: function(e, t, a, n, i) {
                    **this.cotterKeys = JSON.parse(localStorage.getItem("COTTER_KEYS")),**
                    this.apiKey = e,
                    this.redirectURL = t,
                    this.state = a,
                    this.domain = n,
                    this.id = i,
                    this.sessionID = localStorage.getItem("COTTER_SESSION_ID"),
                    localStorage.getItem("COTTER_SESSION_ID") || (this.sessionID = Math.random().toString(36).substring(2, 15),
                    localStorage.setItem("COTTER_SESSION_ID", this.sessionID)),
                    this.checkAllowedOrigin(n, e, t)
                }

The line in bold caused an error for me. im running vue.js

**Comment by foliodev** [comment]
Looks like it appears to be an issue for Brave Browser and not other browsers
<img width="375" alt="Screen Shot 2020-09-16 at 10 56 05 pm" src="https://user-images.githubusercontent.com/865672/93340268-f4c79400-f86f-11ea-9050-13f9c4d341ab.png">

**Comment by putrikarunia** [comment]
Hi @scorpnode , this problem happens when users don't enable cross-site cookies. Unfortunately, this issue is not from this library, but from our iframe in `https://js.cotter.app`. We already have a working solution and releasing it this week.

**Comment by putrikarunia** [comment]
Hi @scorpnode, we have updated our `https://js.cotter.app` to fix this problem. Please try again, if the issue is resolved, you can close this issue. Thanks!

**Comment by foliodev** [comment]
Its fixed! Thanks
