### ISSUE TITLE
Assigning custom fields on JWT/user obj

### ISSUE THREAD

**Issue by smblee** [cotterapp/cotter-js#20]
Hello, wasn't sure where the best place to put these questions was.

I have a use case of assigning custom fields on JWT and the user object (e.g. adding address field, or permission to specific entities). For example, if user is a manager of organization A and B, I want the JWT to include that.

Is this currently possible with cotter?

**Comment by putrikarunia** [comment]
Hi @smblee , sorry for the delay. You can ask questions here but the fastest way to get a response is through [our Slack channel](https://join.slack.com/t/askcotter/shared_invite/zt-dxzf311g-5Mp3~odZNB2DwYaxIJ1dJA).

You can [add custom fields to the JWT token by calling this API](https://docs.cotter.app/getting-access-token/requesting-custom-fields-on-your-jwt-token).
